# ==============================================================
# Personal website of Marcos Verdejo Bosch
# Created: October 2025
# Purpose: Engineering portfolio using Jekyll + GitHub Pages
# Notes:
#   - This file defines global site settings.
#   - "remote_theme" pulls a theme directly from another repo.
# ==============================================================

title: "Marcos Verdejo Bosch"
# Appears in browser tabs and at the top of pages.

description: "Engineering portfolio focused on hardware design, embedded systems, and IoT development."
# Short description for SEO and social previews. Keep it concise.

remote_theme: barryclark/jekyll-now
# This tells GitHub Pages to use the 'jekyll-now' theme from Barry Clark.
# It automatically loads the layout and style without needing local files.

plugins:
  - jekyll-seo-tag   # Adds automatic meta tags for search engines.
  - jekyll-sitemap   # Generates sitemap.xml for SEO.

author:
  name: "Marcos Verdejo Bosch"
  email: contact@marcosverdejobosch.com
  github: marcosverdejo
  linkedin: marcosverdejobosch
# Used by the theme to populate author info and social links.

url: "https://marcosverdejo.github.io"
# Base URL of your site (change to your custom domain later).
